In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import datasets, linear_model

In [4]:

splice_data = pd.read_csv("/Users/harikapanuganty/Desktop/Assignment1/splice.data", header = None)
#splice_data.head() #to check initial data 
splice_data = splice_data.rename(columns={0:"Class", 1:"Donor", 2: "Sequence"})
splice_data.iloc[0].to_dict() #matches the column name to the data from the beginning
#splice_data.head() #check that column name matches data
splice_data["Class"] = splice_data["Class"].str.strip() #strip removes whitespace in beginning and end 
splice_data["Donor"] = splice_data["Donor"].str.strip()
splice_data["Sequence"] = splice_data["Sequence"].str.strip()
splice_data.head()

  Class               Donor                                           Sequence
0    EI    ATRINS-DONOR-521  CCAGCTGCATCACAGGAGGCCAGCGAGCAGGTCTGTTCCAAGGGCC...
1    EI    ATRINS-DONOR-905  AGACCCGCCGGGAGGCGGAGGACCTGCAGGGTGAGCCCCACCGCCC...
2    EI    BABAPOE-DONOR-30  GAGGTGAAGGACGTCCTTCCCCAGGAGCCGGTGAGAAGCGCAGTCG...
3    EI   BABAPOE-DONOR-867  GGGCTGCGTTGCTGGTCACATTCCTGGCAGGTATGGGGCGGGGCTT...
4    EI  BABAPOE-DONOR-2817  GCTCAGCCCCCAGGTCACCCAGGAACTGACGTGAGTGTCCCCATCC...

In [10]:
for x in range(60):
    splice_data["Nucleotide" + str(x)] = splice_data["Sequence"].str[x]

In [11]:
splice_data.head()

,Class,Donor,Sequence,Nucleotide0,Nucleotide1,Nucleotide2,Nucleotide3,Nucleotide4,Nucleotide5,Nucleotide6,...,Nucleotide50,Nucleotide51,Nucleotide52,Nucleotide53,Nucleotide54,Nucleotide55,Nucleotide56,Nucleotide57,Nucleotide58,Nucleotide59
0,EI,ATRINS-DONOR-521,CCAGCTGCATCACAGGAGGCCAGCGAGCAGGTCTGTTCCAAGGGCC...,C,C,A,G,C,T,G,...,A,G,C,C,A,G,T,C,T,G
1,EI,ATRINS-DONOR-905,AGACCCGCCGGGAGGCGGAGGACCTGCAGGGTGAGCCCCACCGCCC...,A,G,A,C,C,C,G,...,G,T,G,C,C,C,C,C,G,C
2,EI,BABAPOE-DONOR-30,GAGGTGAAGGACGTCCTTCCCCAGGAGCCGGTGAGAAGCGCAGTCG...,G,A,G,G,T,G,A,...,C,A,C,G,G,G,G,A,T,G
3,EI,BABAPOE-DONOR-867,GGGCTGCGTTGCTGGTCACATTCCTGGCAGGTATGGGGCGGGGCTT...,G,G,G,C,T,G,C,...,G,G,T,T,T,T,C,C,C,C
4,EI,BABAPOE-DONOR-2817,GCTCAGCCCCCAGGTCACCCAGGAACTGACGTGAGTGTCCCCATCC...,G,C,T,C,A,G,C,...,C,C,T,T,G,A,C,C,C,T

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import datasets, linear_model

In [47]:
#splice_data #is the dataset we're working with 
#columns = "Class Donor Sequence Nucleotide.split()"
##splicedataset = load_splice_data()

##splicedataset.head()

splice_data.head()

,Class,Donor,Sequence,Nucleotide0,Nucleotide1,Nucleotide2,Nucleotide3,Nucleotide4,Nucleotide5,Nucleotide6,...,Nucleotide50,Nucleotide51,Nucleotide52,Nucleotide53,Nucleotide54,Nucleotide55,Nucleotide56,Nucleotide57,Nucleotide58,Nucleotide59
0,EI,ATRINS-DONOR-521,CCAGCTGCATCACAGGAGGCCAGCGAGCAGGTCTGTTCCAAGGGCC...,C,C,A,G,C,T,G,...,A,G,C,C,A,G,T,C,T,G
1,EI,ATRINS-DONOR-905,AGACCCGCCGGGAGGCGGAGGACCTGCAGGGTGAGCCCCACCGCCC...,A,G,A,C,C,C,G,...,G,T,G,C,C,C,C,C,G,C
2,EI,BABAPOE-DONOR-30,GAGGTGAAGGACGTCCTTCCCCAGGAGCCGGTGAGAAGCGCAGTCG...,G,A,G,G,T,G,A,...,C,A,C,G,G,G,G,A,T,G
3,EI,BABAPOE-DONOR-867,GGGCTGCGTTGCTGGTCACATTCCTGGCAGGTATGGGGCGGGGCTT...,G,G,G,C,T,G,C,...,G,G,T,T,T,T,C,C,C,C
4,EI,BABAPOE-DONOR-2817,GCTCAGCCCCCAGGTCACCCAGGAACTGACGTGAGTGTCCCCATCC...,G,C,T,C,A,G,C,...,C,C,T,T,G,A,C,C,C,T

In [48]:
df = pd.DataFrame(splice_data)
df.head()

,Class,Donor,Sequence,Nucleotide0,Nucleotide1,Nucleotide2,Nucleotide3,Nucleotide4,Nucleotide5,Nucleotide6,...,Nucleotide50,Nucleotide51,Nucleotide52,Nucleotide53,Nucleotide54,Nucleotide55,Nucleotide56,Nucleotide57,Nucleotide58,Nucleotide59
0,EI,ATRINS-DONOR-521,CCAGCTGCATCACAGGAGGCCAGCGAGCAGGTCTGTTCCAAGGGCC...,C,C,A,G,C,T,G,...,A,G,C,C,A,G,T,C,T,G
1,EI,ATRINS-DONOR-905,AGACCCGCCGGGAGGCGGAGGACCTGCAGGGTGAGCCCCACCGCCC...,A,G,A,C,C,C,G,...,G,T,G,C,C,C,C,C,G,C
2,EI,BABAPOE-DONOR-30,GAGGTGAAGGACGTCCTTCCCCAGGAGCCGGTGAGAAGCGCAGTCG...,G,A,G,G,T,G,A,...,C,A,C,G,G,G,G,A,T,G
3,EI,BABAPOE-DONOR-867,GGGCTGCGTTGCTGGTCACATTCCTGGCAGGTATGGGGCGGGGCTT...,G,G,G,C,T,G,C,...,G,G,T,T,T,T,C,C,C,C
4,EI,BABAPOE-DONOR-2817,GCTCAGCCCCCAGGTCACCCAGGAACTGACGTGAGTGTCCCCATCC...,G,C,T,C,A,G,C,...,C,C,T,T,G,A,C,C,C,T

In [80]:
import pandas as pd
from sklearn.model_selection import train_test_split
import random

splice_data = pd.read_csv("/Users/harikapanuganty/Desktop/Assignment1/splice.data", header = None)

splice_data.head()

,0,1,2
0,EI,ATRINS-DONOR-521,CCAGCTGCATCACAGGAGGCCAGCGAGCAGG...
1,EI,ATRINS-DONOR-905,AGACCCGCCGGGAGGCGGAGGACCTGCAGGG...
2,EI,BABAPOE-DONOR-30,GAGGTGAAGGACGTCCTTCCCCAGGAGCCGG...
3,EI,BABAPOE-DONOR-867,GGGCTGCGTTGCTGGTCACATTCCTGGCAGGT...
4,EI,BABAPOE-DONOR-2817,GCTCAGCCCCCAGGTCACCCAGGAACTGACGTG...

In [107]:
y = splice_data[0]

random.seed(256)

train, test = train_test_split(splice_data, test_size=0.3)
print(train.shape)
print(test.shape)

(2233, 3)
(957, 3)

In [100]:
import pandas as pd 
df_splice_train = pd.DataFrame(train) #df feeding in values 
df_splice_test = pd.DataFrame(test) #taking in test dataset

In [106]:
splice_train = df_splice_train.groupby([0]).count() #() to make object subscriptable 
#splice_train["Pecent"] = splice_train[]*100/(splice_train)
splice_train.head()

       1     2
0
EI   534   534
IE   543   543
N   1156  1156

In [96]:
splice_test = df_splice_test.groupby([0]).count()
splice_test.head()

      1    2
0
EI  233  233
IE  225  225
N   499  499

In [13]:
splice_data.to_csv("/Users/harikapanuganty/Desktop/splicedata.csv", sep = ',')

In [6]:
splicedata = pd.read_csv("/Users/harikapanuganty/Desktop/Assignment1/splice.data", header = None)

In [7]:
splicedata.head

<bound method NDFrame.head of        0                         1  \
0     EI          ATRINS-DONOR-521
1     EI          ATRINS-DONOR-905
2     EI          BABAPOE-DONOR-30
3     EI         BABAPOE-DONOR-867
4     EI        BABAPOE-DONOR-2817
5     EI        CHPIGECA-DONOR-378
6     EI        CHPIGECA-DONOR-903
7     EI       CHPIGECA-DONOR-1313
8     EI       GCRHBBA1-DONOR-1260
9     EI       GCRHBBA1-DONOR-1590
10    EI        GCRHBBA6-DONOR-461
11    EI        GCRHBBA6-DONOR-795
12    EI       GIBHBGGL-DONOR-2278
13    EI       GIBHBGGL-DONOR-2624
14    EI       GIBHBGGL-DONOR-7198
15    EI       GIBHBGGL-DONOR-7544
16    EI       HUMA1ATP-DONOR-1972
17    EI       HUMA1ATP-DONOR-7932
18    EI       HUMA1ATP-DONOR-9653
19    EI      HUMA1ATP-DONOR-11057
20    EI      HUMA1GLY2-DONOR-1693
21    EI      HUMA1GLY2-DONOR-2251
22    EI      HUMA1GLY2-DONOR-2540
23    EI      HUMA1GLY2-DONOR-3352
24    EI      HUMA1GLY2-DONOR-3606
25    EI       HUMACCYBA-DONOR-289
26    EI      HUMACCYBA-DONOR-1250
27    EI      HUMACCYBA-DONOR-1624
28    EI      HUMACCYBA-DONOR-2504
29    EI      HUMACCYBA-DONOR-2781
...   ..                       ...
3160   N         HUMXYES2-NEG-1741
3161   N          HUMYTEST-NEG-301
3162   N            HUMZFX-NEG-781
3163   N           HUMZFY-NEG-2341
3164   N           HUMZNF8-NEG-661
3165   N         LEMHBDPS-NEG-1441
3166   N           LEMHBGA-NEG-361
3167   N           MACAPOA-NEG-961
3168   N           MACAPOE-NEG-181
3169   N            MACHBA-NEG-421
3170   N           MACHBB-NEG-4141
3171   N           MACHBDPS2-NEG-1
3172   N         MACHBPEA-NEG-2161
3173   N         MACHBPEA-NEG-6721
3174   N        MACHBPSBD-NEG-1141
3175   N         MACPEPSG-NEG-2161
3176   N             MACRSMB-NEG-1
3177   N          MNKHAPSE-NEG-901
3178   N         MNKHAPSE-NEG-5461
3179   N         MNKHBPSBD-NEG-961
3180   N          ORAHBA01-NEG-121
3181   N          ORAHBBE-NEG-2581
3182   N        ORAHBBPSE-NEG-2101
3183   N        ORAHBBPSE-NEG-6661
3184   N          ORAHBG2F-NEG-181
3185   N        ORAHBPSBD-NEG-2881
3186   N         ORAINVOL-NEG-2161
3187   N           ORARGIT-NEG-241
3188   N            TARHBB-NEG-541
3189   N           TARHBD-NEG-1981

                                                      2
0                    CCAGCTGCATCACAGGAGGCCAGCGAGCAGG...
1                    AGACCCGCCGGGAGGCGGAGGACCTGCAGGG...
2                    GAGGTGAAGGACGTCCTTCCCCAGGAGCCGG...
3                   GGGCTGCGTTGCTGGTCACATTCCTGGCAGGT...
4                  GCTCAGCCCCCAGGTCACCCAGGAACTGACGTG...
5                  CAGACTGGGTGGACAACAAAACCTTCAGCGGTA...
6                  CCTTTGAGGACAGCACCAAGAAGTGTGCAGGTA...
7                 CCCTCGTGCGGTCCACGACCAAGACCAGCGGTGA...
8                 TGGCGACTACGGCGCGGAGGCCCTGGAGAGGTGA...
9                 AAGCTGACAGTGGACCCGGTCAACTTCAAGGTGA...
10                 TGGCGACTACGGCGCGGAGGCCCTGGAGAGGTG...
11                 AAGCTGAGAGTGGACCCTGTCAACTTCAAGGTG...
12                GGAAGATGCTGGAGGAGAAACCCTGGGAAGGTAG...
13                AAGCTGCATGTGGATCCTGAGAACTTCAGGGTGA...
14                GGAAGATGTTGGAGGAGAAACCCTGGGAAGGTAG...
15                AAGCTGCATGTGGATCCTGAGAACTTCAGGGTGA...
16                GGCACCACCACTGACCTGGGACAGTGAATCGTAA...
17                TTGCTCTGGTGAATTACATCTTCTTTAAAGGTAA...
18                CACCAAGTTCCTGGAAAATGAAGACAGAAGGTGA...
19               ACAGAGGAGGCACCCCTGAAGCTCTCCAAGGTGAG...
20               GTGCCCATCACCAACGCCACCCTGGACCGGGTGAG...
21               CACGATCTTTCTCAGAGAGTACCAGACCCGGTGAG...
22               AGCGGGAGAATGGGACCGTCTCCAGATACGGTGAG...
23               ATGAGAAGAACTGGGGGCTGTCTTTCTATGGTAGG...
24               TCAGATGTCATGTACACCGACTGGAAAAAGGTAAA...
25                GATCCGCCGCCCGTCCACACCCGCCGCCAGGTAA...
26               CCCTCCATCGTGGGGCGCCCCAGGCACCAGGTAGG...
27               CCCAAGGCCAACCGCGAGAAGATGACCCAGGTGAG...
28               CTGAGGCACTCTTCCAGCCTTCCTTCCTGGGTGAG...
29               GCCCTGGCACCCAGCACAATGAAGATCAAGGTGGG...
...                                                 ...
3160                CTTCACTGCTACAGAGCCATAGTACCAGCCAG...
3161                 GCCGCCCTCCCATTGATTGGCCATGAGGGAA...
3162                   GTAGTTTCAGAAGAAGTATTGGTAGCAGA...
3163                  TTCCGAAGACCTTCAGAAAAGAACCAGCAC...
3164                  CAGGACAAACCCTACAAATGTACTGACTGT...
3165                TTCACCCCACAGGTGCAGGCTGCCTATCAGAA...
3166                  GATGGAATGAACCTGTGTATGGCAGAAATA...
3167                  GGCTTGATCAGGAACTACTGCAGGAATCCA...
3168                  CCAGCAGGCTGAGGGCCAGAGCGGCCAGCC...
3169                   GCTGAGCGACCTGCACGCGCACAAGCTTC...
3170                  TGTGAGCCACACCCTACAGTTGGCCAATCT...
3171                  GAATTCATCCTACAGGTGCAGGCTGCCTAT...
3172                TGACTTTGCACCTGCTCTGTGATTATGACTAT...
3173                GAGAGAGAGACCAGAAATAATCTTGCTTATGC...
3174               TTACCTCTAATCAACAGTTCAATTATGCTTGAA...
3175                GCTGGGGAGAAACCCAAGGTACCTATGGGGCT...
3176                    AAAAGGAAATATCCTCAGATGAAATCTG...
3177                 AGGAAATCTCCTTTGCTCAGATAAGTACACT...
3178                CATACTTGTGCTATCCCCTGCCCTTCTAAATC...
3179                CCTCAGTACCAAACTCATACATCAAACTGTGT...
3180                 CCTGCCGACAAGACCAACGTCAAGACCGCCT...
3181                 CTGGAAGCACTGGATGGAATCTTTTCTGTCT...
3182               TGTTTCTGAAAGAGGGATTAGCCCGTTGTCTTA...
3183               TAAAAAAGACTCTCTGCTGTGGGAGATCCCTTC...
3184                 ATCAATAAGCTCCTAGTCCAGACGCCATGGG...
3185               TCTCTTCCCTTCCCCTCTCTCTTTCTTTCTTTT...
3186                GAGCTCCCAGAGCAGCAAGAGGGCCAGCTGAA...
3187                  TCTCGGGGGCGGCCGGCGCGGCGGGGAGCG...
3188                   ATTCTACTTAGTAAACATAATTTCTTGTG...
3189                  AGGCTGCCTATCAGAAGGTGGTGGCTGGTG...

[3190 rows x 3 columns]>

In [12]:
splice_data.head()

,Class,Donor,Sequence,Nucleotide0,Nucleotide1,Nucleotide2,Nucleotide3,Nucleotide4,Nucleotide5,Nucleotide6,...,Nucleotide50,Nucleotide51,Nucleotide52,Nucleotide53,Nucleotide54,Nucleotide55,Nucleotide56,Nucleotide57,Nucleotide58,Nucleotide59
0,EI,ATRINS-DONOR-521,CCAGCTGCATCACAGGAGGCCAGCGAGCAGGTCTGTTCCAAGGGCC...,C,C,A,G,C,T,G,...,A,G,C,C,A,G,T,C,T,G
1,EI,ATRINS-DONOR-905,AGACCCGCCGGGAGGCGGAGGACCTGCAGGGTGAGCCCCACCGCCC...,A,G,A,C,C,C,G,...,G,T,G,C,C,C,C,C,G,C
2,EI,BABAPOE-DONOR-30,GAGGTGAAGGACGTCCTTCCCCAGGAGCCGGTGAGAAGCGCAGTCG...,G,A,G,G,T,G,A,...,C,A,C,G,G,G,G,A,T,G
3,EI,BABAPOE-DONOR-867,GGGCTGCGTTGCTGGTCACATTCCTGGCAGGTATGGGGCGGGGCTT...,G,G,G,C,T,G,C,...,G,G,T,T,T,T,C,C,C,C
4,EI,BABAPOE-DONOR-2817,GCTCAGCCCCCAGGTCACCCAGGAACTGACGTGAGTGTCCCCATCC...,G,C,T,C,A,G,C,...,C,C,T,T,G,A,C,C,C,T